repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      # Run the ruff formatter
      - id: ruff-format
        args: [--config, pyproject.toml]
      # Run the ruff linter with auto-fix
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --config, pyproject.toml]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: debug-statements
      - id: check-merge-conflict
